import Notofication from "../Screen/Notofication/Notofication";

export const String = {
  // visio: 'Vision : ',
  welcome: "Welcome!",
  simply: 'Lorem ipsum dolor sit amet. consectetur adipiscing elit. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  selectlanguage: "SELECT LANGUAGE",
  please: 'Please Select Your Language',
  welcometothe: "Welcome to the first application that's specify in selling products in a way that make the peocess of buying the products more enjoyable.",
  Sellingpro: 'SELLING PRODUCTS',
  delivery: 'DELIVERY SERIVCES',
  weare: "We are caring about both grnders and different ages.Also we are providing best delivery services.",
  suitableprices: 'SUITABLE PRICES',
  hereineasy: 'Here in easy way you will become the owner of high quality products with very suitable prices.',
  skip: "SKIP",
  login: "LOG IN",
  welcomeback: 'Welcome back! Please login to continue',
  PhoneNumber: "Phone Number",
  password: 'Passward',
  login: 'LOG IN',
  ForgotPassword: "Forgot Password",
  haveanaccount: 'Don’t have an account?',
  CreateNow: " Create Now",
  email: 'Email',
  save: 'SAVE',
  createaccount: 'CREATE ACCOUNT',
  enteryoutinfo: "Enter your information below or continue with social media account",
  Next: 'Next',
  ConfirmPassword: 'Confirm Password',
  IDPASSPORT: 'ID & PASSPORT',
  Pleaseprovide: "Please provide us with a copy of your ID or passport to activate your membership",
  Previous: 'Previous',
  Goback: "Go back to Log In ?",
  PressHere: ' Press Here',
  Fromwhere: "From where do you want to upload the picture",
  Wewill: "We will send an Activation code to this number",
  Edit: "Edit",
  Submit: "Submit",
  Verification: "OTP Verification",
  EnterOTp: "Enter the OTP sent to -",
  PopularCategory: "Popular Category",
  Headphone: "Headphone",
  Camera: 'Camera',
  HomeAccessories: 'Home Accessories',
  SpecialProducts: "Special Products",
  MusicanNomore: "Music and No more",
  Music: '10% off for One of the best headphones in the world',
  JBL: 'JBL WH-1000XM4',
  WatcExcellent: 'Wireless Over-ear Noise Canceling Headphones',
  CellularSmart: 'Cellular 44mm Smart Watch - Excellent',
  USD: '$2 USD',
  $: '/$ 35 USD',
  Products: 'Products',
  Apple: 'Apple Watch SE Series',
  Allaccessories: 'All Accessories',
  home: 'Home',
  Transactions: 'Transactions',
  AboutUs: 'About Us',
  ShareApp: 'Share App',
  RateApp: "Rate App",
  Languages: "Languages",
  logout: 'LogOut',
  Wireless: 'Wireless Over-ear Industry Leading Noise Canceling Headphones',
  Price: 'Price',
  USD: "$ 12 USD",
  Real: "Real Price: $ 30 USD",
  BID: 'BID',
  ProductID: "Product ID",
  Condition: "Condition",
  Alert: 'Alert',
  Guarantee: 'This products have a 15 days Guarantee.',
  Discription: "Discription",
  LoremIpsum: "Lorem Ipsum is simply dummy text of the printin gand typesetting.Lorem Ipsum is simply dummy text of the printin gand typesetting",
  ViewMore: "View More",
  Attributes: 'Attributes',
  Auctions: "Auctions",
  acutioner: "Acutioner",
  views: 'Views',
  ReletedProduct: "Releted Product",
  BIDS: "BIDS",
  thewishlistitems: 'Please Log in to see the wish list items',
  USD: '$2 USD',
  Wining: "Wining",
  Order: "ORDER",
  price: 'Price : ',
  discount: 'Discount : ',
  auction: 'Auction Fee : ',
  Delivery: 'Delivery Price : ',
  TotalPri: 'Total Price : ',
  Totalpay: 'Total Payment : ',
  MassagerNeck: "Massager Neck Massager with Heat, 3 speed...",
  shiatsumassage: 'Massager neck massager with heat, 3 speeds for shiatsu massage',
  CONTACTUS: 'CONTACT US',
  istedbelow: 'Feel free to reach out to us at any of the locations listed below.',
  profile: 'Profile',
  FullName: 'Full Name',
  ChangeLocation: 'Change Location',
  Language: 'Language',
  Password: 'Password',
  ConfirmPassword: "Confirm Password",
  DeleteAccount: 'Delete Account ',
  savechange: "Save Changes",
  Areyousure: "Are you sure to delete this object?",
  deni: 'Deni',
  delete: "Delete",
  deleteobject: "Delete ",
  MYWISHLIST: 'MY WISH LIST',
  TRANSACTIONS: "TRANSACTIONS",
  CurrentBalance: 'Current Balance',
  Order: "Order",
  winninghistory: 'WINING HISTORY',
  winingtext: 'Disney Frozen Joy Toy 19389 2- Accessory Set 18 Pieces Multi...',
  available: 'A new version is available',
  Performance: "Performance and stability improvements  ",
  updatapp: 'Update App',
  Upsfound: 'Ups!...no results found',
  Pleasesearch: "Please try another search",
  tryagain: 'Try Again',
  InternetConnection: "Ooops ! No Internet Connection",
  startBestbidagain: 'It seems there is something wrong with your internet connection. Please connect to the internet and start Bestbid again. ',
  SelectLocation:'Select Location',
  YourLocation:'Your Location',
  AnaIllinois:'2972 Westheimer Rd. Santa Ana, Illinois 85486 ',
  SaveAs:'Save As',
  SelectProvince:'Select Province',
  city:'City',
  District:'District',
  SAVEADDRESS:"SAVE ADDRESS",
  Notofication:'NOTOFICATION'
}